INSERT INTO questions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
('What is the capital of India?', 'Mumbai', 'New Delhi', 'Kolkata', 'Chennai', 'b'),
('Which planet is known as the Red Planet?', 'Earth', 'Mars', 'Jupiter', 'Venus', 'b'),
('Who wrote the national anthem of India?', 'Bankim Chandra Chatterjee', 'Rabindranath Tagore', 'Sarojini Naidu', 'Jawaharlal Nehru', 'b'),
('Who is known as the Father of Computers?', 'Charles Babbage', 'Alan Turing', 'Tim Berners-Lee', 'Bill Gates', 'a'),
('Which gas do plants absorb?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen', 'c'),
('Who discovered gravity?', 'Albert Einstein', 'Isaac Newton', 'Galileo', 'Bohr', 'b'),
('Largest ocean in the world?', 'Indian', 'Atlantic', 'Arctic', 'Pacific', 'd'),
('National animal of India?', 'Peacock', 'Tiger', 'Elephant', 'Lion', 'b'),
('Gift of Statue of Liberty to USA came from?', 'Germany', 'France', 'Italy', 'Spain', 'b'),
('Chemical formula of water?', 'H2O', 'CO2', 'O2', 'NaCl', 'a'),
('First President of India?', 'Rajendra Prasad', 'Nehru', 'Radhakrishnan', 'Zakir Hussain', 'a'),
('Dark Continent is?', 'Asia', 'Europe', 'Africa', 'Australia', 'c'),
('Longest river in the world?', 'Amazon', 'Nile', 'Ganga', 'Yangtze', 'b'),
('Instrument to measure earthquakes?', 'Barometer', 'Thermometer', 'Seismograph', 'Speedometer', 'c'),
('Who invented the telephone?', 'Bell', 'Edison', 'Tesla', 'Watt', 'a'),
('Smallest planet?', 'Mars', 'Mercury', 'Venus', 'Earth', 'b'),
('India gained independence in?', '1945', '1946', '1947', '1948', 'c'),
('Liquid metal at room temp?', 'Iron', 'Mercury', 'Gold', 'Sodium', 'b'),
('Land of Rising Sun?', 'China', 'Japan', 'Korea', 'Thailand', 'b'),
('Hardest natural substance?', 'Gold', 'Iron', 'Diamond', 'Platinum', 'c'),
('Fastest land animal?', 'Lion', 'Tiger', 'Cheetah', 'Leopard', 'c'),
('Largest desert?', 'Gobi', 'Sahara', 'Thar', 'Kalahari', 'b'),
('Which is the tallest mountain?', 'K2', 'Kanchenjunga', 'Everest', 'Makalu', 'c'),
('Which gas is used for breathing underwater?', 'Nitrogen', 'Oxygen', 'Carbon dioxide', 'Helium', 'd'),
('How many continents are there?', '5', '6', '7', '8', 'c'),
('Closest star to Earth?', 'Moon', 'Proxima Centauri', 'Sun', 'Sirius', 'c'),
('Which country invented paper?', 'India', 'Egypt', 'China', 'Greece', 'c'),
('Largest mammal?', 'Elephant', 'Blue Whale', 'Shark', 'Giraffe', 'b'),
('What is HCl?', 'Hydrogen chloride', 'Hydrochloric acid', 'Hydrogen carbonate', 'Helium chloride', 'b'),
('Which organ pumps blood?', 'Brain', 'Lungs', 'Heart', 'Liver', 'c'),
('Primary source of energy is?', 'Sun', 'Wind', 'Coal', 'Water', 'a'),
('Which is the smallest bone?', 'Femur', 'Stapes', 'Ulna', 'Fibula', 'b'),
('National bird of India?', 'Crow', 'Sparrow', 'Peacock', 'Eagle', 'c'),
('Currency of Japan?', 'Dollar', 'Yen', 'Won', 'Euro', 'b'),
('Largest country by area?', 'India', 'USA', 'Russia', 'China', 'c'),
('Speed of light is approx?', '1,50,000 km/s', '2,00,000 km/s', '3,00,000 km/s', '4,00,000 km/s', 'c'),
('Which vitamin is from sunlight?', 'A', 'B', 'C', 'D', 'd'),
('Who wrote Romeo and Juliet?', 'Shakespeare', 'Milton', 'Wordsworth', 'Keats', 'a'),
('Which is a programming language?', 'HTML', 'Python', 'CSS', 'XML', 'b'),
('Which is the nearest planet to the Sun?', 'Earth', 'Mars', 'Mercury', 'Venus', 'c'),
('What is the freezing point of water?', '0°C', '10°C', '50°C', '100°C', 'a'),
('Which gas is most abundant in air?', 'Oxygen', 'Nitrogen', 'Hydrogen', 'CO2', 'b'),
('Which is the largest volcano?', 'Krakatoa', 'Mauna Loa', 'Etna', 'Vesuvius', 'b'),
('Which festival is of lights?', 'Holi', 'Diwali', 'Eid', 'Christmas', 'b'),
('Which animal lays eggs?', 'Cow', 'Dog', 'Bat', 'Duck', 'd'),
('Which is the longest bone?', 'Femur', 'Tibia', 'Humerus', 'Radius', 'a'),
('World’s largest island?', 'Greenland', 'Iceland', 'Madagascar', 'Sumatra', 'a'),
('Who discovered penicillin?', 'Newton', 'Alexander Fleming', 'Curie', 'Einstein', 'b'),
('Which organ purifies blood?', 'Stomach', 'Kidneys', 'Lungs', 'Skin', 'b');
